### ISSUE TITLE
项目在Tablet设备上产生一个异常

### ISSUE THREAD

**Issue by lbz2020** [Trisia/CircleCameraPreview#1]
项目运行设备：rockchip rk3288
报错提示：W/CameraBase: An error occurred while connecting to camera 1: Status(-8): '4: validateConnectLocked:850: No camera device with ID "" available'
E/SurfaceView: Exception configuring surface
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:546)
        at android.hardware.Camera.open(Camera.java:392)
        at com.github.cliven.circlecamerapreview.CircleCameraPreview.openCamera(CircleCameraPreview.java:174)
        at com.github.cliven.circlecamerapreview.CircleCameraPreview.surfaceCreated(CircleCameraPreview.java:347)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2477)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1469)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7196)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
我在网上搜了错误，还是没能解决。
换成移动设备是可以正常运行项目的。

**Comment by lbz2020** [comment]
解决了。原因是rk3288设备的后置摄像头改成前置的了。导致读不出来id
